[package]
name = "desktop2mqtt"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
tokio = { version = "0.2", features = ["full"] }
mqtt-async-client = "0.1"
xidlehook-core = { git = "https://gitlab.com/maxjoehnk/xidlehook", branch = "fix-arm-build", features = ["tokio"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
anyhow = "1"
futures-util = "0.3"
